/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage { 'userId' : Principal, 'message' : string }
export interface QuizScore {
  'userId' : Principal,
  'score' : bigint,
  'timestamp' : bigint,
}
export interface UserProfile {
  'theme' : string,
  'username' : string,
  'gamesPlayed' : bigint,
  'chatsSent' : bigint,
  'totalScore' : bigint,
  'avatar' : bigint,
}
export interface _SERVICE {
  'addChatMessage' : ActorMethod<[string], undefined>,
  'addQuizScore' : ActorMethod<[bigint], undefined>,
  'createOrUpdateProfile' : ActorMethod<[string, bigint, string], undefined>,
  'getAllProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllQuizScores' : ActorMethod<[], Array<[Principal, Array<QuizScore>]>>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getProfile' : ActorMethod<[], UserProfile>,
  'getQuizScores' : ActorMethod<[], Array<QuizScore>>,
  'getTheme' : ActorMethod<[], string>,
  'switchTheme' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];