/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserProfile = IDL.Record({
  'theme' : IDL.Text,
  'username' : IDL.Text,
  'gamesPlayed' : IDL.Nat,
  'chatsSent' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'avatar' : IDL.Nat,
});
export const QuizScore = IDL.Record({
  'userId' : IDL.Principal,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const ChatMessage = IDL.Record({
  'userId' : IDL.Principal,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addChatMessage' : IDL.Func([IDL.Text], [], []),
  'addQuizScore' : IDL.Func([IDL.Nat], [], []),
  'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'getAllProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllQuizScores' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(QuizScore)))],
      ['query'],
    ),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'getQuizScores' : IDL.Func([], [IDL.Vec(QuizScore)], ['query']),
  'getTheme' : IDL.Func([], [IDL.Text], ['query']),
  'switchTheme' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserProfile = IDL.Record({
    'theme' : IDL.Text,
    'username' : IDL.Text,
    'gamesPlayed' : IDL.Nat,
    'chatsSent' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'avatar' : IDL.Nat,
  });
  const QuizScore = IDL.Record({
    'userId' : IDL.Principal,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const ChatMessage = IDL.Record({
    'userId' : IDL.Principal,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addChatMessage' : IDL.Func([IDL.Text], [], []),
    'addQuizScore' : IDL.Func([IDL.Nat], [], []),
    'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'getAllProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllQuizScores' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(QuizScore)))],
        ['query'],
      ),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'getQuizScores' : IDL.Func([], [IDL.Vec(QuizScore)], ['query']),
    'getTheme' : IDL.Func([], [IDL.Text], ['query']),
    'switchTheme' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };